const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const app = fs.readFileSync(path.join(root, "src/renderer/src/App.vue"), "utf8");

assert.doesNotMatch(app, /topbar-right|class="topbar"|floatingTopbarVisible|handleMainScroll/, "全局悬浮顶部导航应彻底删除");
assert.match(app, /<main\s+ref="mainScrollElement"\s+class="main-scroll"/, "主滚动区引用仍应用于页面回顶");

assert.match(app, /local-home-date/, "本地主页缺少日期与模式信息");
assert.match(app, /local-home-greeting/, "本地主页缺少问候标题");
assert.match(app, /local-home-random/, "本地主页缺少随机漫游入口");
assert.match(app, /local-home-last-played/, "本地主页缺少上次播放区域");
assert.match(app, /\.local-home-page\s*\{[^}]*width:\s*min\(1180px/, "本地主页组件需要缩短为 1180px 居中布局");
assert.match(app, /\.local-home-page\s*\{[^}]*margin-top:\s*18px/, "本地主页顶部应保留舒适留白，避免问候文字贴边");
assert.match(app, /\.local-home-page\s*\{[^}]*gap:\s*42px/, "本地主页组件之间需要保留更舒展的纵向间距");
assert.match(app, /local-home-track-title/, "本地主页缺少歌曲标题信息");
assert.match(app, /local-home-track-meta/, "本地主页缺少歌曲格式信息");
assert.doesNotMatch(app, /<span>\{\{\s*localHomeTrackQuality\s*\}\}<\/span>/, "本地主页歌曲信息不应再显示 48kHz 音质字样");
assert.match(app, /class="local-home-last-played"[\s\S]*--home-accent-primary[\s\S]*localHomeTrack\.primary[\s\S]*--home-accent-secondary[\s\S]*localHomeTrack\.secondary/, "首页大控件右半部分渐变应跟随当前歌曲封面色");
assert.match(app, /class="local-home-last-played"[\s\S]*--home-cover-image[\s\S]*localHomeCoverUrl/, "首页大控件背景应直接读取当前歌曲封面生成环境色");
assert.match(app, /\.local-home-last-played\s*\{[^}]*var\(--home-accent-primary\)[^}]*var\(--home-accent-secondary\)/, "首页大控件背景应使用歌曲封面色变量生成渐变");
assert.match(app, /\.local-home-last-played::before\s*\{[^}]*background-image:\s*var\(--home-cover-image\)[^}]*filter:\s*blur\(/, "首页大控件右侧应使用封面图生成柔和环境色层");
assert.match(app, /\.local-home-progress-track\s*\{[^}]*height:\s*5px/, "首页播放进度条需要加粗");
assert.match(app, /\.local-home-progress-track span\s*\{[^}]*linear-gradient\(90deg,\s*#2f6df6,\s*#14a88d\)/, "首页播放进度条应使用蓝绿渐变");
assert.match(app, /class="local-home-progress-input"[\s\S]*type="range"[\s\S]*@pointerdown="beginSeek"[\s\S]*@input="handleProgressInput"[\s\S]*@pointerup="finishSeekFromEvent"/, "首页播放进度条应支持点击和拖拽跳转");
assert.match(app, /\.local-home-progress-input\s*\{[^}]*position:\s*absolute[^}]*cursor:\s*pointer/, "首页播放进度条需要提供覆盖整条轨道的可交互区域");
assert.match(app, /local-home-cover/, "本地主页缺少右侧封面区域");
assert.match(app, /local-home-stats-panel/, "本地主页缺少音乐库统计面板");
assert.match(app, /localLibraryStats/, "音乐库统计面板缺少统计数据来源");
assert.match(app, /\.local-home-stats-panel\s*\{[^}]*background:\s*transparent/, "音乐库统计面板背景应与主页背景融为一体");
assert.doesNotMatch(app, /\.local-home-stat:nth-child\(odd\)[\s\S]{0,120}background/, "音乐库统计项不应再使用间隔色块背景");
assert.doesNotMatch(app, /\.local-home-stat:nth-child\(even\)[\s\S]{0,120}background/, "音乐库统计项不应再使用交替色块背景");
assert.match(app, /local-home-recent-panel/, "本地主页缺少最近添加模块");
assert.match(app, /localRecentlyAddedTracks/, "最近添加模块缺少真实曲库数据来源");
assert.match(app, /createdAt/, "最近添加需要映射歌曲添加时间");
assert.match(app, /最近添加/, "最近添加模块缺少标题");
assert.match(app, /刚收进音乐库的声音，先听为敬。/, "最近添加模块缺少说明文字");
assert.match(app, /全部歌曲/, "最近添加模块缺少全部歌曲入口");
assert.match(app, /\.local-home-recent-panel\s*\{[^}]*background:\s*transparent/, "最近添加模块背景应与主页背景融为一体");
assert.match(app, /local-listening-footprints/, "本地主页缺少聆听足迹模块");
assert.match(app, /聆听足迹/, "聆听足迹模块缺少标题");
assert.match(app, /每一次重播，都在慢慢画出你的音乐偏好。/, "聆听足迹模块缺少副标题");
assert.match(app, /最近播放/, "聆听足迹模块缺少最近播放入口");
assert.match(app, /TOP TRACKS/, "聆听足迹模块缺少歌曲排行榜");
assert.match(app, /按累计聆听时长排序/, "歌曲排行榜缺少排序说明");
assert.match(app, /CALENDAR/, "聆听足迹模块缺少听歌日历");
assert.match(app, /localTopListeningTracks/, "歌曲排行榜应从本地聆听统计生成");
assert.match(app, /listeningCalendarDays/, "听歌日历应从本地聆听统计生成");
assert.match(app, /shiftListeningMonth/, "听歌日历缺少上个月和下个月切换逻辑");
assert.match(app, /selectListeningCalendarDate/, "听歌日历日期缺少选中逻辑");
assert.match(app, /\.local-listening-footprints\s*\{[^}]*background:\s*transparent/, "聆听足迹外层背景应与主页大背景融合");
assert.match(app, /local-featured-albums/, "本地主页缺少专辑精选模块");
assert.match(app, /专辑精选/, "专辑精选模块缺少标题");
assert.match(app, /从头到尾听完一张专辑，是留给音乐最温柔的时间。/, "专辑精选模块缺少描述");
assert.match(app, /全部专辑/, "专辑精选模块缺少全部专辑入口");
assert.match(app, /localFeaturedAlbums/, "专辑精选需要从本地专辑数据展示");
assert.match(app, /localAlbums/, "专辑精选需要从本地曲库聚合专辑表");
assert.match(app, /openLocalAlbum/, "专辑卡片缺少进入专辑详情逻辑");
assert.match(app, /selectedLocalAlbum/, "专辑详情缺少选中专辑状态");
assert.match(app, /\.local-featured-albums\s*\{[^}]*background:\s*transparent/, "专辑精选外层背景应与主页大背景融合");
assert.match(app, /\.local-album-card:hover\s+\.[\s\S]*transform:\s*translateY\(-4px\)/, "专辑封面需要 hover 上浮动画");
for (const item of ["首歌曲", "张专辑", "位艺术家", "收藏总时长"]) {
  assert.match(app, new RegExp(item), `音乐库统计面板缺少 ${item}`);
}
assert.match(app, /playRandomLocalTrack/, "随机漫游入口缺少播放逻辑");
assert.match(app, /\.local-home-play \.play-icon/, "本地主页播放按钮缺少播放三角图标样式");
assert.match(app, /\.local-home-play \.pause-icon/, "本地主页播放按钮缺少暂停图标样式");
assert.match(app, /localHomeTrack/, "本地主页没有使用上次播放歌曲数据");
assert.match(app, /首收藏里抽一首/, "随机漫游说明没有体现本地收藏数量");
assert.match(app, /shouldShowLocalEmptyRoom/, "本地模式缺少未选择音乐文件夹的空房间状态");
assert.match(app, /localLibraryHydrated = ref\(false\)/, "本地音乐库恢复完成前不能误判为空");
assert.match(app, /shouldShowLocalEmptyRoom[\s\S]*localLibraryHydrated\.value[\s\S]*!hasLocalLibraryContent\.value/, "空房间状态需要等本地音乐库恢复完成后再显示");
assert.match(app, /localLibraryHydrated\.value = true/, "加载或扫描本地音乐库后需要标记恢复完成");
assert.match(app, /local-empty-room/, "本地模式缺少空房间界面");
assert.match(app, /\.local-empty-room\s*\{[^}]*gap:\s*42px/, "空音乐库页面组件之间需要保留更舒展的纵向间距");
assert.match(app, /local-empty-card/, "空房间界面需要使用大白卡承载内容");
assert.match(app, /local-empty-message/, "空房间界面需要显示选择或扫描提示");
assert.match(app, /这里还很安静/, "空房间界面缺少主标题");
assert.match(app, /Twilight Echo · 唱片房间/, "空房间界面缺少唱片房间说明");
assert.match(app, /添加音乐库文件夹/, "空房间界面缺少添加音乐库文件夹按钮");
assert.match(app, /批量扫描/, "空房间界面缺少批量扫描标签");
assert.match(app, /无损格式/, "空房间界面缺少无损格式标签");
assert.match(app, /聆听统计/, "空房间界面缺少聆听统计标签");
assert.match(app, /chooseMusicFolderAndScan/, "空房间添加按钮需要选择并扫描音乐文件夹");
assert.doesNotMatch(app, /window\.prompt/, "选择本地音乐库不能再使用浏览器输入框");
assert.match(app, /const shouldOpenLocalHomeAfterScan = shouldShowLocalEmptyRoom\.value[\s\S]*activeView\.value = "home"/, "空房间选择文件夹并扫描后需要回到本地主页");
assert.match(app, /<PlayerBar\s+v-if="!shouldHidePlayerBar && !showSongDetail && !miniPlayerVisible"/, "未选择本地文件夹、打开歌曲详情或迷你播放器时外层播放栏需要隐藏");

console.log("本地主页契约通过");
