const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const app = fs.readFileSync(path.join(root, "src/renderer/src/App.vue"), "utf8");
const mini = fs.readFileSync(path.join(root, "src/renderer/src/components/MiniPlayer.vue"), "utf8");
const main = fs.readFileSync(path.join(root, "src/main/main.ts"), "utf8");
const preload = fs.readFileSync(path.join(root, "src/preload/preload.ts"), "utf8");
const env = fs.readFileSync(path.join(root, "src/renderer/src/env.d.ts"), "utf8");

assert.match(mini, /queue:\s*MiniQueueTrack\[\]/, "迷你播放器应接收当前播放队列");
assert.match(mini, /queueOpen:\s*boolean/, "迷你播放器应接收队列展开状态");
assert.match(mini, /queueShellOpen:\s*boolean/, "迷你播放器应独立接收窗口展开壳层状态");
assert.match(mini, /playlists:\s*MiniPlaylist\[\]/, "迷你播放器应接收可添加的普通歌单");
assert.match(mini, /'is-queue-open':\s*props\.queueShellOpen/, "队列退场与窗口缩放期间应由应用保持展开布局");
assert.match(mini, /class="mini-queue-panel"[\s\S]*v-for="\(track, index\) in props\.queue"/, "迷你播放器下方应显示播放列表");
assert.doesNotMatch(mini, /class="mini-queue-header"/, "迷你播放列表不应保留标题、数量和收起提示栏");
assert.match(mini, /class="mini-queue-track"[\s\S]*class="mini-queue-copy"[\s\S]*class="mini-queue-actions"[\s\S]*mini-queue-play[\s\S]*mini-queue-like[\s\S]*mini-queue-more/, "播放、收藏和更多按钮应统一位于歌曲右侧");
assert.match(mini, /import \{ CircleEllipsis, Heart, Pause, Play \} from "lucide-vue-next"/, "队列操作应复用统一线宽的 Lucide 图标");
assert.match(mini, /<Play[^>]*:size="16"[^>]*:stroke-width="1\.6"/, "未播放歌曲应显示细线空心播放图标");
assert.match(mini, /<Pause[^>]*:size="16"[^>]*:stroke-width="1\.6"/, "当前播放歌曲应显示同规格暂停图标");
assert.match(mini, /<Heart[^>]*:size="16"[^>]*:stroke-width="1\.6"[^>]*:fill="track\.liked \? 'currentColor' : 'none'"/, "爱心应使用同规格描边并仅在收藏时填充");
assert.match(mini, /<CircleEllipsis[^>]*:size="16"[^>]*:stroke-width="1\.6"/, "更多按钮应使用同规格圆圈三点图标");
assert.match(mini, /\.mini-queue-play,\.mini-queue-like,\.mini-queue-more\s*\{[^}]*width:\s*28px;[^}]*height:\s*28px;[^}]*border-radius:\s*50%/, "三个操作按钮应使用统一尺寸和圆形悬浮区域");
assert.match(mini, /function toggleQueueTrackPlayback\(track: MiniQueueTrack\)[\s\S]{0,180}isCurrentTrack\(track\)[\s\S]{0,180}emit\("toggle"\)[\s\S]{0,180}emit\("queueTrackPlay", track\)/, "队列歌曲应通过统一入口切换当前歌曲或播放其他歌曲");
assert.match(mini, /class="mini-queue-copy"[^>]*@click\.stop="toggleQueueTrackPlayback\(track\)"/, "点击歌曲文字应与右侧播放按钮使用同一切换逻辑");
assert.match(mini, /class="mini-queue-play"[\s\S]{0,320}@click\.stop="toggleQueueTrackPlayback\(track\)"/, "点击右侧播放按钮应使用统一切换逻辑");
assert.match(mini, /\.mini-queue-like\s*\{[^}]*color:\s*#252b2d/, "未收藏爱心应使用黑色细线轮廓");
assert.match(mini, /\.mini-queue-like\.liked\s*\{[^}]*color:\s*#ff6674/, "已收藏爱心应使用红色实心状态");
assert.match(mini, /从播放列表移除[\s\S]*添加到歌单[\s\S]*复制歌曲信息/, "更多菜单应提供三项指定操作");
assert.match(mini, /props\.playlists[\s\S]*新建歌单/, "添加到歌单界面应列出已有歌单并支持新建");
assert.match(mini, /window\.addEventListener\("blur", dismissQueue\)/, "原生迷你窗口失焦时应收起队列");
assert.match(mini, /document\.addEventListener\("pointerdown", handleOutsidePointerDown, true\)/, "点击迷你播放器外部时应收起队列");
assert.match(mini, /\.mini-close-button\s*\{[^}]*opacity:\s*0[^}]*pointer-events:\s*none/, "关闭按钮平时应隐藏且不可点击");
assert.match(mini, /\.mini-player:hover \.mini-close-button[^}]*opacity:\s*1[^}]*pointer-events:\s*auto/, "悬浮迷你播放器时才显示关闭按钮");
assert.match(mini, /\.mini-queue-track\.active[^}]*color:\s*#16a36a/, "当前播放歌曲应使用绿色高亮");
assert.match(mini, /\.mini-queue-list\s*\{[^}]*overflow-y:\s*auto/, "歌曲过多时队列应垂直滚动");
assert.match(mini, /\.mini-queue-list\s*\{[^}]*height:\s*208px/, "迷你队列视口应固定容纳四首歌曲");
assert.match(mini, /\.mini-queue-track\s*\{[^}]*height:\s*52px/, "迷你队列每首歌曲应使用固定行高");
assert.match(mini, /\.mini-queue-track:hover \.mini-queue-actions[^}]*opacity:\s*1/, "歌曲操作按钮应仅在悬浮或键盘聚焦时显示");
assert.match(mini, /\.mini-queue-list:not\(\.is-scrolling\)::-webkit-scrollbar-thumb[^}]*background:\s*transparent/, "滚动条应在未滚动时隐藏");
assert.match(mini, /queueTransitionEnd:\s*\[\]/, "迷你播放器应在队列退场结束后通知应用");
assert.match(mini, /<Transition name="mini-queue" @after-leave="finishQueueLeave">/, "队列应在 CSS 退场完成后再结束展开状态");
assert.match(mini, /\.mini-queue-enter-active,\.mini-queue-leave-active\s*\{[^}]*transform-origin:\s*top center[^}]*will-change:\s*opacity,transform[^}]*transition:[^}]*opacity 220ms[^}]*transform 220ms/, "播放列表动效应与卡片及原生窗口使用相同的 220ms 时长");
assert.match(mini, /\.mini-queue-enter-from,\.mini-queue-leave-to\s*\{[^}]*opacity:\s*0[^}]*transform:\s*translateY\(-10px\) scaleY\(\.96\)/, "播放列表应从顶部平滑展开并向上收起");
assert.match(mini, /\.mini-player\s*\{[^}]*grid-template-rows:\s*132px minmax\(0,1fr\)/, "卡片收缩时顶部播放器必须固定高度，不能被剩余空间拉到中间");
assert.match(mini, /\.mini-player\.is-native-window\s*\{[^}]*grid-template-rows:\s*129px minmax\(0,1fr\)/, "原生窗口缩放期间顶部播放器也必须保持固定高度");

assert.match(app, /const miniQueueVisible = ref\(false\)/, "应用应维护迷你队列展开状态");
assert.match(app, /const miniQueueShellOpen = ref\(false\)/, "应用应单独维护队列窗口壳层状态");
assert.match(app, /if \(!nativeMiniMode\.value\)\s*\{\s*miniQueueShellOpen\.value = visible;\s*miniQueueVisible\.value = visible;\s*return;/, "网页模式应同时收缩卡片并淡出列表，不能分成两拍");
assert.match(app, /window\.listenMusic\?\.setMiniQueueExpanded/, "应用应通知原生窗口同步展开或收起");
assert.match(app, /const leaveFinished = waitForMiniQueueLeave\(\);[\s\S]{0,120}miniQueueVisible\.value\s*=\s*false;[\s\S]{0,260}Promise\.all\(\[\s*leaveFinished,\s*window\.listenMusic\?\.setMiniQueueExpanded\(false\)\s*\]\)/, "收起时 CSS 退场与原生窗口缩放必须并行执行");
assert.match(app, /Promise\.all[\s\S]{0,360}miniQueueShellOpen\.value\s*=\s*false/, "退场与窗口缩放都结束后才能折叠顶部播放器壳层");
assert.match(app, /<MiniPlayer[\s\S]*:queue="playbackQueue"[\s\S]*:queue-open="miniQueueVisible"[\s\S]*:queue-shell-open="miniQueueShellOpen"[\s\S]*:playlists="playlistOverviewSource"/, "应用应向迷你播放器传入队列内容与独立壳层状态");
assert.match(app, /@queue-transition-end="handleMiniQueueTransitionEnd"/, "应用应接收迷你队列退场结束事件");
assert.match(app, /@queue="toggleMiniQueue"[\s\S]*@queue-track-play="playQueueTrack"[\s\S]*@queue-track-like="toggleTrackLiked"[\s\S]*@queue-track-remove="removeQueueTrack"/, "迷你队列应复用现有播放、收藏和移除逻辑");
assert.match(app, /@queue-track-add-playlist="addMiniQueueTrackToPlaylist"[\s\S]*@queue-track-create-playlist="createMiniPlaylistWithTrack"[\s\S]*@queue-track-copy="copyMiniQueueTrackInfo"/, "迷你队列更多菜单应接入歌单与复制逻辑");

assert.match(main, /MINI_QUEUE_WINDOW_HEIGHT\s*=\s*396/, "原生迷你队列高度应固定容纳四首歌曲");
assert.match(main, /ipcMain\.handle\("set-mini-queue-expanded"/, "主进程应提供迷你队列窗口尺寸切换 IPC");
assert.match(main, /async function setMiniQueueExpanded[\s\S]*animateWindowBounds/, "队列展开与收起应平滑调整窗口尺寸");
assert.match(main, /ipcMain\.handle\("copy-text"[\s\S]*clipboard\.writeText/, "复制歌曲信息应由主进程可靠写入系统剪贴板");
assert.match(preload, /setMiniQueueExpanded:\s*\(expanded:\s*boolean\)\s*=>\s*ipcRenderer\.invoke\("set-mini-queue-expanded", expanded\)/, "preload 应暴露迷你队列尺寸切换方法");
assert.match(preload, /copyText:\s*\(value:\s*string\)\s*=>\s*ipcRenderer\.invoke\("copy-text", value\)/, "preload 应通过 IPC 提供歌曲信息复制能力");
assert.match(env, /setMiniQueueExpanded\(expanded:\s*boolean\):\s*Promise<boolean>/, "渲染层应声明迷你队列尺寸桥接类型");
assert.match(env, /copyText\(value:\s*string\):\s*Promise<boolean>/, "渲染层应声明异步复制文本桥接类型");

console.log("迷你播放器播放列表契约通过");
