const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const app = fs.readFileSync(path.join(root, "src/renderer/src/App.vue"), "utf8");
const api = fs.readFileSync(path.join(root, "src/renderer/src/services/api.ts"), "utf8");
const main = fs.readFileSync(path.join(root, "src/main/main.ts"), "utf8");
const preload = fs.readFileSync(path.join(root, "src/preload/preload.ts"), "utf8");
const env = fs.readFileSync(path.join(root, "src/renderer/src/env.d.ts"), "utf8");

assert.match(app, /class="playlist-detail-page"/, "歌单详情应使用独立页面容器");
assert.match(app, /\.playlist-detail-page\s*\{[^}]*width:\s*min\(1364px,\s*100%\)/, "歌单详情宽度应基于当前工作区，侧栏展开时不得超出屏幕");
assert.doesNotMatch(app, /\.playlist-detail-page\s*\{[^}]*width:[^;}]*100vw/, "歌单详情宽度不应按整个窗口计算");
assert.doesNotMatch(app, /if \(view === "playlists"\)[\s\S]{0,160}openDefaultPlaylistDetail\(\)/, "点击侧栏歌单应停留在歌单总览页，不应直接打开收藏歌单详情");
assert.match(app, /class="playlist-overview-page"/, "点击侧栏歌单应进入独立歌单总览页");
assert.match(app, /class="playlist-overview-title"[\s\S]*歌单[\s\S]*共 \{\{ playlistOverviewPlaylists\.length \}\} 份歌单/, "歌单总览标题右侧应显示歌单数量");
assert.match(app, /长按歌单拖动排序，顺序保存在当前设备。/, "歌单总览应显示拖动排序提示");
assert.match(app, /class="playlist-overview-search"[\s\S]*placeholder="搜索歌曲、歌手、专辑或文件夹"/, "歌单总览右上角应有指定搜索框");
assert.match(app, /class="create-playlist-card"[\s\S]*创建歌单/, "歌单总览应显示创建歌单卡片");
assert.match(app, /class="create-playlist-card"[\s\S]*@click="openPlaylistCreateDialog"/, "点击创建歌单卡片应打开创建弹窗");
assert.match(app, /class="playlist-overview-grid"[\s\S]*class="create-playlist-card"[\s\S]*v-for="playlist in playlistOverviewPlaylists"/, "歌单总览创建卡片应排在歌单卡片前面");
assert.match(app, /class="playlist-overview-card-shell"[\s\S]*draggable="true"[\s\S]*@dragstart="startPlaylistOverviewDrag\(playlist\.id\)"[\s\S]*@drop="dropPlaylistOverviewCard\(playlist\.id\)"/, "歌单卡片应支持拖动排序");
assert.match(app, /PLAYLIST_OVERVIEW_ORDER_STORAGE_KEY[\s\S]*persistPlaylistOverviewOrder/, "歌单排序应持久化在当前设备");
assert.match(app, /activeView !== 'playlists'[\s\S]*class="section-block track-section"/, "歌单总览不应显示继续聆听歌曲列表");
assert.match(app, /class="playlist-detail-back"[\s\S]*←\s*返回/, "歌单详情顶部应有返回按钮");
assert.match(app, /class="playlist-detail-title"[\s\S]*selectedPlaylist\.title/, "歌单详情标题应展示当前歌单名");
assert.match(app, /class="playlist-detail-title-row"[\s\S]*class="playlist-detail-meta"[\s\S]*selectedPlaylistTrackSummary/, "歌单详情标题旁应展示歌曲数量和总时长");
assert.match(app, /playlist-detail-toolbar[\s\S]*playlist-tool-rename[\s\S]*playlist-tool-copy[\s\S]*playlist-tool-cover/, "右侧工具栏只保留重命名、复制、设置封面三个按钮");
assert.match(app, /class="playlist-detail-controls"[\s\S]*class="playlist-detail-toolbar"[\s\S]*class="playlist-detail-filter"/, "歌单详情工具按钮组应移动到筛选器左边");
assert.match(app, /\.playlist-detail-controls \{[^}]*margin-right:\s*32px/, "歌单详情右侧控制组应整体左移，避免贴近滚动条");
assert.match(app, /\.playlist-detail-controls\s*\{[^}]*min-width:\s*0/, "歌单详情右侧控制组应允许随工作区收缩");
assert.match(app, /\.playlist-detail-title \{[^}]*font-size: clamp\(28px,3vw,36px\)/, "歌单详情标题字号应参考较小标题尺寸");
assert.match(app, /\.playlist-overview-title \{[^}]*font-size: clamp\(28px,3vw,36px\)/, "歌单总览标题字号应参考较小标题尺寸");
assert.doesNotMatch(app, /class="playlist-detail-toolbar"[\s\S]{0,800}M3U8/, "歌单详情不应保留 M3U8 导出按钮");
assert.doesNotMatch(app, /class="playlist-detail-toolbar"[\s\S]{0,800}playlist-tool-download|class="playlist-detail-toolbar"[\s\S]{0,800}playlist-tool-locate/, "歌单详情不应保留下载或定位等多余工具按钮");
assert.match(app, /@click="openPlaylistRenameDialog"/, "重命名按钮应打开复用创建样式的弹窗");
assert.match(app, /@click="duplicateSelectedPlaylist"/, "复制按钮应复制歌单并跳转到新歌单详情");
assert.match(app, /@click="choosePlaylistCover"/, "封面按钮应打开本地图片选择");
assert.match(app, /class="playlist-quick-actions"[\s\S]*播放全部[\s\S]*随机播放/, "标题下方应有播放全部和随机播放");
assert.match(app, /class="playlist-detail-filter"[\s\S]*筛选器/, "歌单详情应保留筛选器下拉按钮");
assert.match(app, /class="playlist-filter-panel"/, "筛选器应弹出独立面板");
assert.match(app, /v-model="playlistFilter\.folder"/, "筛选器应有文件夹下拉");
assert.match(app, /v-model="playlistFilter\.source"/, "筛选器应有来源下拉");
assert.doesNotMatch(app, /v-model="playlistFilter\.(sort|order)"|resetPlaylistFilter/, "筛选器应移除排序、升降序和重置逻辑");
assert.doesNotMatch(app, /class="playlist-filter-panel"[\s\S]{0,1200}(DSD|位深|采样率|无损)/, "歌单详情筛选器不应保留音质类筛选项");
assert.match(app, /filteredPlaylistTracks/, "歌单详情歌曲列表应按当前歌单筛选条件实时计算");
assert.match(app, /class="playlist-track-card"[\s\S]*draggable="true"[\s\S]*@dragstart="startPlaylistTrackDrag\(track\)"[\s\S]*@drop(?:\.[a-z]+)*="dropPlaylistTrack\(track\)"/, "普通歌单歌曲行应默认支持拖拽排序");
assert.match(app, /PLAYLIST_TRACK_ORDER_STORAGE_KEY[\s\S]*persistPlaylistTrackOrder/, "普通歌单歌曲顺序应持久保存在当前设备");
assert.match(app, /class="playlist-track-table-head"[\s\S]*#\s*<\/span>[\s\S]*标题[\s\S]*专辑[\s\S]*时长/, "歌单详情歌曲列表应有贴近页面背景的表头");
assert.match(app, /\.playlist-track-container \{[^}]*background: var\(--app-card-background\);[^}]*box-shadow: var\(--app-card-shadow\);/, "歌单详情歌曲列表应使用白色卡片层级");
assert.match(app, /\.playlist-track-card\.active \{[^}]*background: var\(--app-playing-background\);/, "当前播放行应使用全局浅米色高亮");
assert.match(app, /class="playlist-track-card"/, "有歌曲时应展示歌单歌曲行列表");
assert.match(app, /class="playlist-empty-state"[\s\S]*暂无内容[\s\S]*通过左侧菜单「歌单 → 添加文件夹」导入音乐/, "无歌曲时应展示指定空态文案");
assert.match(app, /class="playlist-name-dialog"/, "重命名应复用创建歌单弹窗风格");
assert.match(app, /playlistNameDialogMode\.value === "create"/, "创建歌单应复用同一个弹窗样式");
assert.match(app, /playlistNameError/, "重命名弹窗应校验歌单名不能为空");
assert.match(app, /persistLocalPlaylists/, "歌单重命名、复制、封面应持久化");
assert.match(app, /resolvePlaylistCover/, "普通歌单封面应通过统一的首曲封面规则派生");
assert.match(app, /orderedPlaylistTracksForCover/, "普通歌单封面应读取手动排序后的歌曲列表");
assert.match(app, /PLAYLIST_COVER_PATH_STORAGE_KEY[\s\S]*persistPlaylistCoverPaths/, "用户设置的歌单封面应独立持久化");
assert.match(api, /export async function selectPlaylistCoverImage/, "渲染层应提供选择歌单封面的 API");
assert.match(api, /document\.createElement\("input"\)[\s\S]*input\.type\s*=\s*"file"/, "非 Electron 环境应回退到图片文件选择器");
assert.match(api, /\^\(\?:https\?:\|file:\|data:\|blob:\)/, "已可直接加载的封面地址不应错误拼接后端地址");
assert.match(main, /select-playlist-cover-image/, "主进程应提供图片文件选择 IPC");
assert.match(preload, /selectCoverImage/, "预加载桥应暴露图片选择能力");
assert.match(env, /selectCoverImage\(\): Promise<string \| null>/, "Window 类型应声明图片选择桥");

console.log("歌单详情页契约通过");
