const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const playerBar = fs.readFileSync(path.join(root, "src/renderer/src/components/PlayerBar.vue"), "utf8");
const app = fs.readFileSync(path.join(root, "src/renderer/src/App.vue"), "utf8");

assert.match(playerBar, /class=\"player-bar\"\s*:class=\"\{[^}]*is-sidebar-collapsed/, "播放器需要知道侧栏是否收起");
assert.match(playerBar, /sidebarCollapsed\??:\s*boolean/, "播放器缺少侧栏状态属性");
assert.match(playerBar, /ambient\??:\s*boolean/, "播放器应提供仅详情页启用的环境色属性");
assert.match(playerBar, /is-ambient[^}]*props\.ambient/, "播放器应按环境色属性切换样式类");
assert.match(playerBar, /\.player-bar\s*\{[^}]*right:\s*auto[^}]*bottom:\s*12px[^}]*left:\s*calc\(224px\s*\+\s*\(100vw\s*-\s*224px\)\s*\/\s*2\)[^}]*width:\s*min\(1180px,\s*calc\(100vw\s*-\s*224px\s*-\s*48px\)\)[^}]*border-radius:\s*20px/, "侧栏展开时播放器应在主内容区居中且不覆盖侧栏");
assert.match(playerBar, /\.player-bar\s*\{[^}]*--player-bar-height:\s*68px[^}]*height:\s*var\(--player-bar-height\)[^}]*min-height:\s*var\(--player-bar-height\)[^}]*padding:\s*5px\s+15px/, "全局底部播放器应使用参考图的 68px 通栏高度");
assert.match(playerBar, /\.cover-expand\s*\{[^}]*width:\s*46px[^}]*height:\s*46px/, "播放器封面应使用参考图的紧凑尺寸");
assert.match(playerBar, /\.mini-cover\s*\{[^}]*width:\s*46px[^}]*height:\s*46px/, "播放器封面内容应保持正方形且不被裁切");
assert.match(playerBar, /\.transport\s*\{[^}]*grid-template-rows:\s*44px\s+14px[^}]*gap:\s*0/, "中央播放控制与进度条应按参考图上下分层");
assert.match(playerBar, /\.transport-controls \.player-control-button\.play-button\.compact\s*\{[^}]*width:\s*44px[^}]*height:\s*44px/, "主播放按钮应覆盖共享紧凑样式并保持 44px 正圆");
assert.match(playerBar, /\.progress-input\s*\{[^}]*height:\s*10px/, "进度条应保留足够的可拖拽区域");
assert.match(playerBar, /\.progress-row\s*\{[^}]*grid-template-columns:\s*34px\s+minmax\(0,1fr\)\s+34px/, "进度时间应分列显示在轨道左右");
assert.match(playerBar, /\.progress-times\s*\{[^}]*display:\s*contents/, "进度时间应参与进度行栅格对齐");
assert.match(playerBar, /\.track-copy strong,\.track-copy span\s*\{[^}]*text-overflow:\s*ellipsis[^}]*white-space:\s*nowrap/, "歌曲信息应保持单行并在超长时显示省略号");
assert.match(playerBar, /\.player-bar\s*\{[^}]*background:\s*rgba\(255,255,255,\.98\)/, "普通页面播放器应使用接近纯白的通栏背景");
assert.match(playerBar, /\.player-bar\s*\{[^}]*overflow:\s*visible/, "播放器应允许音量弹层向上溢出显示");
assert.match(playerBar, /\.player-bar::before\s*\{[^}]*border-radius:\s*inherit/, "播放器环境色覆盖层应自行继承圆角");
assert.match(playerBar, /\.player-volume-panel\s*\{[^}]*left:\s*50%[^}]*right:\s*auto[^}]*translateX\(-50%\)/, "音量弹层应以音量按钮容器的中心线定位");
assert.match(playerBar, /\.player-bar\.is-ambient\.is-theme-ready::before\s*\{[^}]*linear-gradient\([^}]*--detail-player-start[^}]*--detail-player-end/, "详情页播放器应使用封面环境色渐变");
assert.match(playerBar, /@property\s+--detail-player-start\s*\{[^}]*syntax:\s*"<color>"/, "播放器环境色变量应注册为可插值颜色");
assert.match(playerBar, /@property\s+--detail-player-end\s*\{[^}]*syntax:\s*"<color>"/, "播放器第二环境色变量应注册为可插值颜色");
assert.match(playerBar, /--detail-player-start\s+400ms\s+ease[^;]*--detail-player-end\s+400ms\s+ease/, "播放器环境色切换应使用 0.4 秒平滑过渡");
assert.match(playerBar, /is-theme-ready[^}]*ambientThemeReady/, "进入歌曲详情时应在下一帧启动播放器主题过渡");
assert.match(playerBar, /requestAnimationFrame[\s\S]*ambientThemeReady\.value\s*=\s*true/, "播放器环境色应在挂载后的下一帧渐变进入");
assert.match(playerBar, /\.player-bar\.is-ambient\.is-theme-ready[^}]*linear-gradient\([^}]*--detail-player-start[^}]*--detail-player-end/, "详情页播放器应通过渐变覆盖层平滑显现环境色");
assert.match(playerBar, /\.player-bar\.is-ambient\.is-theme-ready[\s\S]*\.track-copy strong[\s\S]*transition:\s*color\s+400ms\s+ease/, "播放器文字主题色应同步平滑过渡");
assert.match(playerBar, /@media\s*\(prefers-reduced-motion:\s*reduce\)[\s\S]*transition-duration:\s*0\.01ms/, "系统减少动态效果时应关闭颜色动画");
assert.match(playerBar, /box-shadow:\s*0\s+-8px\s+24px/, "通栏播放器应使用轻柔的顶部阴影");
assert.match(playerBar, /\.transport-controls \.player-control-button\.play-button\.compact\s*\{[^}]*background:\s*#68369a/, "底部播放按钮应使用参考图的紫色");
assert.match(playerBar, /\.transport-controls \.play-button:hover\s*\{[^}]*background:\s*#572985/, "底部播放按钮悬停应使用更深的紫色");
assert.match(playerBar, /playMode:\s*\"shuffle\"\s*\|\s*\"sequence\"\s*\|\s*\"single\"\s*\|\s*\"loop\"/, "底部播放器需要读取全局播放模式");
assert.match(playerBar, /mode:\s*\[\]/, "底部播放器播放模式按钮需要触发切换事件");
assert.match(playerBar, /mini:\s*\[\]/, "底部播放器需要提供迷你播放器事件");
assert.match(playerBar, /hifi:\s*\[\]/, "底部播放器需要提供 HiFi 控制台事件");
assert.doesNotMatch(playerBar, /connection-state/, "底部播放器右侧不应显示后端连接状态");
assert.match(playerBar, /kind="like"[\s\S]*player-mode-button[\s\S]*player-volume-wrap[\s\S]*kind="queue"[\s\S]*player-mini-button[\s\S]*lyrics-button[\s\S]*player-hifi-button/, "右侧功能区应按参考图排列并显示音量入口");
assert.match(playerBar, /linear-gradient\(90deg,\s*#2f6df6\s*0%,\s*#14a88d\s*var\(--progress\),\s*#dfe6ef\s*var\(--progress\)\s*100%\)/, "底部播放器进度条已播放部分应使用蓝绿渐变");
assert.match(playerBar, /\.progress-input::-(?:webkit-slider-runnable-track|moz-range-track)\s*\{[^}]*height:\s*4px/, "底部播放器进度轨道应随高度同步压缩");
assert.match(playerBar, /\.progress-input::-webkit-slider-thumb\s*\{[^}]*background:\s*transparent[^}]*box-shadow:\s*none/, "底部播放器不应显示 WebKit 黑色进度滑块");
assert.match(playerBar, /\.progress-input::-moz-range-thumb\s*\{[^}]*background:\s*transparent[^}]*box-shadow:\s*none/, "底部播放器不应显示 Firefox 黑色进度滑块");
assert.doesNotMatch(playerBar, /\.progress-slider-wrap\.is-preview::after\s*\{/, "底部播放器不应额外绘制黑色试听终点圆点");
assert.match(playerBar, /progress-times/, "底部播放器进度时间应独立显示在进度条下方");
assert.match(playerBar, /\.player-bar\.is-sidebar-collapsed\s*\{[^}]*left:\s*50%[^}]*width:\s*min\(1180px,\s*calc\(100vw\s*-\s*48px\)\)/, "侧栏收起后播放器仍应保持窗口居中和相同宽度");
assert.match(playerBar, /transition:[^}]*left\s+280ms\s+ease[^}]*width\s+280ms\s+ease/, "播放器应与侧栏使用相同的 280ms 位移动画");
assert.match(playerBar, /@media\s*\(max-width:\s*980px\)[\s\S]*?\.player-bar\s*\{[^}]*left:\s*calc\(72px\s*\+\s*\(100vw\s*-\s*72px\)\s*\/\s*2\)[^}]*width:\s*min\(1180px,\s*calc\(100vw\s*-\s*72px\s*-\s*44px\)\)/, "窄侧栏下播放器应在 72px 之外的内容区居中");
assert.match(playerBar, /@media\s*\(max-width:\s*720px\)[\s\S]*?\.player-bar\s*\{[^}]*right:\s*12px[^}]*bottom:\s*12px[^}]*left:\s*84px[^}]*width:\s*auto[^}]*transform:\s*none/, "手机宽度下播放器应避开 72px 侧栏并保留 12px 间距");
assert.match(playerBar, /@media\s*\(max-width:\s*720px\)[\s\S]*?\.player-bar\.is-sidebar-collapsed\s*\{[^}]*left:\s*12px[^}]*width:\s*auto/, "手机宽度侧栏收起后播放器应恢复全窗口边距");
assert.match(app, /<PlayerBar[\s\S]*:sidebar-collapsed=\"sidebarCollapsed\"/, "App 未向播放器传递侧栏状态");

console.log("播放器悬浮布局契约通过");
