server:
  port: 17890

spring:
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB

listenmusic:
  catalog:
    provider: netease
  providers:
    netease:
      base-url: http://127.0.0.1:3000
    qq:
      base-url: http://127.0.0.1:3300
